###

GET http://localhost:8080/api/products

###

POST http://localhost:8080/api/menu
Content-Type: application/json

{"menuName":"Test","link":"/test"}

###
GET http://localhost:8080/api/users
Content-Type: application/json

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "name":"John","email":"john@example.com"
}